server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800 # tomcat最大线程数，默认为200
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 10 #最小空闲数
      maximum-pool-size: 30 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      auto-commit: true
      idle-timeout: 120000 #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟。minimumIdle<maximumPoolSize时生效
      pool-name: DatebookHikariCP #自定义连接池名
      max-lifetime: 1800000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      connection-timeout: 30000 #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      validation-timeout: 3000 #指定验证连接有效性的超时时间，默认是5秒
      connection-test-query: SELECT 1
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  jta:
    atomikos:
      properties:
        recovery:
          forget-orphaned-log-entries-delay:
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.uiho.zlwu.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
